import httpx
import os
from upstash_redis import Redis
from typing import Optional

from expensemgr.utils.secrets import UPSTASH_REDIS_REST_URL, UPSTASH_REDIS_REST_TOKEN
from expensemgr.utils.logger import expense_mgr_logger

# Path to corporate CA bundle exported from the system trust store.
# Generated by running: python3 -c "import ssl,base64; ctx=ssl.create_default_context(); ..."
_CA_BUNDLE = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "corporate-ca-bundle.pem"
)


class RedisEngine:
    _r: Optional[Redis] = None
    _instance: Optional["RedisEngine"] = None

    @classmethod
    def _initalise(cls):
        cls._r = Redis(
            url=UPSTASH_REDIS_REST_URL,
            token=UPSTASH_REDIS_REST_TOKEN,
            rest_retries=3,
            rest_retry_interval=1,
        )
        # Replace the internal httpx client to use the corporate CA bundle.
        # Required because the corporate proxy injects its own cert into the
        # TLS chain, which the default httpx trust store does not include.
        # Only apply when the bundle file is present (local/corporate environment).
        ca_bundle = os.path.normpath(_CA_BUNDLE)
        verify = ca_bundle if os.path.isfile(ca_bundle) else True
        cls._r._http._client = httpx.Client(timeout=None, verify=verify)

    @classmethod
    def get_instance(cls) -> "RedisEngine":
        if cls._instance is None:
            cls._instance = super(RedisEngine, cls).__new__(cls)
            cls._initalise()
        return cls._instance

    @classmethod
    def get_redis_instance(cls) -> Redis:
        redis_engine_instance = cls.get_instance()
        return redis_engine_instance._r


#     updated_at = exchange_rates.get("meta").get("last_updated_at")
#     with redis_instance.pipeline() as pipe:
#         for code, code_data in exchange_rates.get("data").items():
#             code_data["updated_at"] = updated_at
#             pipe.hset(
#                 name=f"EXCHANGE_RATE:{code}",
#                 mapping=code_data,

#             )
#         pipe.execute()

# print(
#     redis_instance.hgetall(
#         name="EXCHANGE_RATE:INR"
#     )
# )
# print(redis_instance.hget(
#     name="EXCHANGE_RATE:INR",
#     key="value"
# ))
