"""base_revision

Revision ID: 550139955241
Revises: 
Create Date: 2025-11-02 16:44:40.060814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550139955241'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('currency_key', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('currency_desc', sa.String(length=255), nullable=False),
    sa.Column('meta_changed_dttm', sa.DateTime(), nullable=True),
    sa.Column('meta_changed_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('currency_key', name='currency_pk'),
    schema='money_schema'
    )
    op.create_index(op.f('ix_money_schema_currency_currency_code'), 'currency', ['currency_code'], unique=True, schema='money_schema')
    op.create_index(op.f('ix_money_schema_currency_currency_key'), 'currency', ['currency_key'], unique=False, schema='money_schema')
    op.create_table('division_by',
    sa.Column('division_by_key', sa.Integer(), nullable=False),
    sa.Column('division_by_type', sa.String(length=10), nullable=False),
    sa.Column('division_by_type_desc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('division_by_key', name='division_by_pk'),
    schema='money_schema'
    )
    op.create_table('user',
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('meta_changed_dttm', sa.DateTime(), nullable=True),
    sa.Column('user_active_ind', sa.Boolean(), server_default='TRUE', nullable=True),
    sa.PrimaryKeyConstraint('user_key', name='user_pk'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_user_email'), 'user', ['email'], unique=True, schema='user_schema')
    op.create_index(op.f('ix_user_schema_user_user_key'), 'user', ['user_key'], unique=False, schema='user_schema')
    op.create_index(op.f('ix_user_schema_user_username'), 'user', ['username'], unique=True, schema='user_schema')
    op.create_table('expense',
    sa.Column('expense_key', sa.Integer(), nullable=False),
    sa.Column('primary_user_key', sa.Integer(), nullable=False),
    sa.Column('currency_key', sa.Integer(), nullable=False),
    sa.Column('division_by_key', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('expense_desc', sa.String(length=255), nullable=True),
    sa.Column('meta_changed_dttm', sa.DateTime(), nullable=True),
    sa.Column('meta_changed_by', sa.Integer(), nullable=True),
    sa.Column('expense_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['currency_key'], ['money_schema.currency.currency_key'], ),
    sa.ForeignKeyConstraint(['currency_key'], ['money_schema.currency.currency_key'], name='expense_fk02'),
    sa.ForeignKeyConstraint(['division_by_key'], ['money_schema.division_by.division_by_key'], ),
    sa.ForeignKeyConstraint(['division_by_key'], ['money_schema.division_by.division_by_key'], name='expense_fk03'),
    sa.ForeignKeyConstraint(['primary_user_key'], ['user_schema.user.user_key'], ),
    sa.ForeignKeyConstraint(['primary_user_key'], ['user_schema.user.user_key'], name='expense_fk01'),
    sa.PrimaryKeyConstraint('expense_key', name='expense_pk'),
    schema='money_schema'
    )
    op.create_index(op.f('ix_money_schema_expense_expense_key'), 'expense', ['expense_key'], unique=False, schema='money_schema')
    op.create_table('expense_ver',
    sa.Column('expense_ver_key', sa.Integer(), nullable=False),
    sa.Column('expense_key', sa.Integer(), nullable=False),
    sa.Column('primary_user_key', sa.Integer(), nullable=False),
    sa.Column('secondary_user_key', sa.Integer(), nullable=False),
    sa.Column('expense_share', sa.Float(), nullable=False),
    sa.Column('expense_ver_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['expense_key'], ['money_schema.expense.expense_key'], ),
    sa.ForeignKeyConstraint(['expense_key'], ['money_schema.expense.expense_key'], name='expense_ver_fk01'),
    sa.ForeignKeyConstraint(['primary_user_key'], ['user_schema.user.user_key'], ),
    sa.ForeignKeyConstraint(['primary_user_key'], ['user_schema.user.user_key'], name='expense_ver_fk02'),
    sa.PrimaryKeyConstraint('expense_ver_key', name='expense_ver_pk'),
    schema='money_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_ver', schema='money_schema')
    op.drop_index(op.f('ix_money_schema_expense_expense_key'), table_name='expense', schema='money_schema')
    op.drop_table('expense', schema='money_schema')
    op.drop_index(op.f('ix_user_schema_user_username'), table_name='user', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_user_user_key'), table_name='user', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_user_email'), table_name='user', schema='user_schema')
    op.drop_table('user', schema='user_schema')
    op.drop_table('division_by', schema='money_schema')
    op.drop_index(op.f('ix_money_schema_currency_currency_key'), table_name='currency', schema='money_schema')
    op.drop_index(op.f('ix_money_schema_currency_currency_code'), table_name='currency', schema='money_schema')
    op.drop_table('currency', schema='money_schema')
    # ### end Alembic commands ###
