"""empty message

Revision ID: a6841cb6419d
Revises: 
Create Date: 2025-02-08 10:00:21.507725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6841cb6419d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pk'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_users_email'), 'users', ['email'], unique=True, schema='user_schema')
    op.create_index(op.f('ix_user_schema_users_user_id'), 'users', ['user_id'], unique=False, schema='user_schema')
    op.create_index(op.f('ix_user_schema_users_username'), 'users', ['username'], unique=True, schema='user_schema')
    op.create_table('currency',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('abbr', sa.String(length=10), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_schema.users.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_schema.users.user_id'], name='currency_fk01'),
    sa.PrimaryKeyConstraint('currency_id', name='currency_pk'),
    schema='money_schema'
    )
    op.create_index(op.f('ix_money_schema_currency_abbr'), 'currency', ['abbr'], unique=True, schema='money_schema')
    op.create_index(op.f('ix_money_schema_currency_currency_id'), 'currency', ['currency_id'], unique=False, schema='money_schema')
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['money_schema.currency.currency_id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['money_schema.currency.currency_id'], name='expense_fk02'),
    sa.ForeignKeyConstraint(['user_id'], ['user_schema.users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_schema.users.user_id'], name='expense_fk01'),
    sa.PrimaryKeyConstraint('expense_id', name='expense_pk'),
    schema='money_schema'
    )
    op.create_index(op.f('ix_money_schema_expenses_expense_id'), 'expenses', ['expense_id'], unique=False, schema='money_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_money_schema_expenses_expense_id'), table_name='expenses', schema='money_schema')
    op.drop_table('expenses', schema='money_schema')
    op.drop_index(op.f('ix_money_schema_currency_currency_id'), table_name='currency', schema='money_schema')
    op.drop_index(op.f('ix_money_schema_currency_abbr'), table_name='currency', schema='money_schema')
    op.drop_table('currency', schema='money_schema')
    op.drop_index(op.f('ix_user_schema_users_username'), table_name='users', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_user_id'), table_name='users', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_email'), table_name='users', schema='user_schema')
    op.drop_table('users', schema='user_schema')
    # ### end Alembic commands ###
